# Generated by Django 5.1.3 on 2024-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_description_ky_task_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
